2024-12-18 08:49:55.931 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration presence_simulation which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-18 08:49:55.938 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration iphonedetect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-18 08:49:55.943 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pirateweather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-18 08:49:55.947 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-18 08:49:55.950 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration simple_wyze_vac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-18 08:49:55.954 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-18 08:49:55.958 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration gasbuddy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-18 08:49:55.962 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration reolink_discovery which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-18 08:49:55.965 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration wyzeapi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-18 08:49:55.969 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration auto_backup which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-18 08:50:01.824 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2024-12-18 08:50:01.906 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=175 from 2024-12-13 11:47:04.393903)
2024-12-18 08:50:34.314 ERROR (SyncWorker_5) [custom_components.iphonedetect.device_tracker] [Errno -2] Name does not resolve
2024-12-18 08:50:37.004 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0x75c0c6a35e80>: Failed to establish a new connection: [Errno 113] Host is unreachable'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2024-12-18 08:50:41.486 ERROR (MainThread) [homeassistant.components.sensor] Platform smartthings does not generate unique IDs. ID 1a6d0984-19b4-426e-86d8-77906f2fe112.energy already exists - ignoring sensor.outlet_energy_meter
2024-12-18 08:50:41.487 ERROR (MainThread) [homeassistant.components.sensor] Platform smartthings does not generate unique IDs. ID 1a6d0984-19b4-426e-86d8-77906f2fe112.power already exists - ignoring sensor.outlet_power_meter
2024-12-18 08:50:41.888 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'Start Vacuum When Everyone is Away' could not be validated and has been disabled: expected dictionary @ data['actions'][0]. Got 's'
extra keys not allowed @ data['data']. Got {'entity_id': 'vacuum.first_floor_vacuum', 'rooms': ['switch.swv_office', 'switch.swv_kitchen', 'switch.swv_kitchentable']}
2024-12-18 08:50:43.035 WARNING (MainThread) [homeassistant.components.group.sensor] Unable to use state. Only numerical states are supported, entity sensor.lumi_lumi_weather_battery_2 with value unavailable excluded from calculation in sensor.zigbee_battery
2024-12-18 08:50:43.035 WARNING (MainThread) [homeassistant.components.group.sensor] Unable to use state. Only numerical states are supported, entity sensor.lumi_lumi_motion_ac02_battery_2 with value unavailable excluded from calculation in sensor.zigbee_battery
2024-12-18 08:50:43.036 WARNING (MainThread) [homeassistant.components.group.sensor] Unable to use state. Only numerical states are supported, entity sensor.masterbathroomtemp_battery with value unavailable excluded from calculation in sensor.zigbee_battery
2024-12-18 08:50:43.036 WARNING (MainThread) [homeassistant.components.group.sensor] Unable to use state. Only numerical states are supported, entity sensor.basementpowderroomtemp_battery with value unavailable excluded from calculation in sensor.zigbee_battery
2024-12-18 08:50:43.036 WARNING (MainThread) [homeassistant.components.group.sensor] Unable to use state. Only numerical states are supported, entity sensor.lumi_lumi_sensor_motion_aq2_battery with value unavailable excluded from calculation in sensor.zigbee_battery
2024-12-18 08:50:43.036 WARNING (MainThread) [homeassistant.components.group.sensor] Unable to use state. Only numerical states are supported, entity sensor.lumi_lumi_sensor_motion_aq2_battery_2 with value unavailable excluded from calculation in sensor.zigbee_battery
2024-12-18 08:50:43.037 WARNING (MainThread) [homeassistant.components.group.sensor] Unable to use state. Only numerical states are supported, entity sensor.lumi_lumi_motion_ac02_battery with value unavailable excluded from calculation in sensor.zigbee_battery
2024-12-18 08:50:43.037 WARNING (MainThread) [homeassistant.components.group.sensor] Unable to use state. Only numerical states are supported, entity sensor.lumi_lumi_sensor_wleak_aq1_battery with value unavailable excluded from calculation in sensor.zigbee_battery
2024-12-18 08:50:43.037 WARNING (MainThread) [homeassistant.components.group.sensor] Unable to use state. Only numerical states are supported, entity sensor.lumi_lumi_sensor_wleak_aq1_battery_2 with value unavailable excluded from calculation in sensor.zigbee_battery
2024-12-18 08:50:43.038 WARNING (MainThread) [homeassistant.components.group.sensor] Unable to use state. Only numerical states are supported, entity sensor.lumi_lumi_weather_battery_4 with value unavailable excluded from calculation in sensor.zigbee_battery
2024-12-18 08:50:43.038 WARNING (MainThread) [homeassistant.components.group.sensor] Unable to use state. Only numerical states are supported, entity sensor.lumi_lumi_weather_battery_3 with value unavailable excluded from calculation in sensor.zigbee_battery
2024-12-18 08:50:46.343 ERROR (SyncWorker_20) [custom_components.iphonedetect.device_tracker] [Errno -2] Name does not resolve
2024-12-18 08:50:58.352 ERROR (SyncWorker_8) [custom_components.iphonedetect.device_tracker] [Errno -2] Name does not resolve
2024-12-18 08:51:10.361 ERROR (SyncWorker_20) [custom_components.iphonedetect.device_tracker] [Errno -2] Name does not resolve
2024-12-18 08:51:22.380 ERROR (SyncWorker_21) [custom_components.iphonedetect.device_tracker] [Errno -2] Name does not resolve
2024-12-18 08:51:34.392 ERROR (SyncWorker_0) [custom_components.iphonedetect.device_tracker] [Errno -2] Name does not resolve
2024-12-18 08:51:40.108 ERROR (SyncWorker_7) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0x75c0b750f5c0>: Failed to establish a new connection: [Errno 113] Host is unreachable'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2024-12-18 08:51:46.399 ERROR (SyncWorker_10) [custom_components.iphonedetect.device_tracker] [Errno -2] Name does not resolve
2024-12-18 08:51:58.404 ERROR (SyncWorker_5) [custom_components.iphonedetect.device_tracker] [Errno -2] Name does not resolve
2024-12-18 08:52:10.420 ERROR (SyncWorker_13) [custom_components.iphonedetect.device_tracker] [Errno -2] Name does not resolve
2024-12-18 08:52:22.437 ERROR (SyncWorker_11) [custom_components.iphonedetect.device_tracker] [Errno -2] Name does not resolve
2024-12-18 08:52:34.441 ERROR (SyncWorker_18) [custom_components.iphonedetect.device_tracker] [Errno -2] Name does not resolve
2024-12-18 08:52:43.209 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0x75c0b0b07a70>: Failed to establish a new connection: [Errno 113] Host is unreachable'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2024-12-18 08:52:46.450 ERROR (SyncWorker_0) [custom_components.iphonedetect.device_tracker] [Errno -2] Name does not resolve
2024-12-18 08:52:58.455 ERROR (SyncWorker_4) [custom_components.iphonedetect.device_tracker] [Errno -2] Name does not resolve
2024-12-18 08:53:10.462 ERROR (SyncWorker_10) [custom_components.iphonedetect.device_tracker] [Errno -2] Name does not resolve
2024-12-18 08:53:22.467 ERROR (SyncWorker_17) [custom_components.iphonedetect.device_tracker] [Errno -2] Name does not resolve
2024-12-18 08:53:34.474 ERROR (SyncWorker_18) [custom_components.iphonedetect.device_tracker] [Errno -2] Name does not resolve
2024-12-18 08:53:46.312 ERROR (SyncWorker_21) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0x75c0b2aa4b90>: Failed to establish a new connection: [Errno 113] Host is unreachable'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2024-12-18 08:53:46.485 ERROR (SyncWorker_0) [custom_components.iphonedetect.device_tracker] [Errno -2] Name does not resolve
2024-12-18 08:53:58.490 ERROR (SyncWorker_4) [custom_components.iphonedetect.device_tracker] [Errno -2] Name does not resolve
